import type { EventRecord } from "@/modules/events/domain/types";

export function readyEvent(changes: Partial<EventRecord> = {}): EventRecord {
  const photo = {
    id: "photo-1",
    eventId: "event-1",
    status: "READY" as const,
    sortOrder: 0,
    stagingObjectKey: null,
    dashboardThumbnailKey: "test/event-1/photo-1/thumb.webp",
    listingCardKey: "test/event-1/photo-1/card.webp",
    galleryKey: "test/event-1/photo-1/gallery.webp",
    coverDisplayKey: "test/event-1/photo-1/cover.webp",
    dashboardThumbnailHash: "a".repeat(64),
    listingCardHash: "b".repeat(64),
    galleryHash: "c".repeat(64),
    coverDisplayHash: "d".repeat(64),
    sourceContentType: "image/jpeg",
    sourceSize: 100,
    width: 1200,
    height: 800,
    errorCode: null,
    readyAt: new Date("2026-07-20T00:00:00.000Z"),
    reservation: null,
  };
  return {
    id: "event-1",
    organizerId: "organizer-1",
    ownerUserId: "user-1",
    organizerDisplayName: "Bakersfield Organizer",
    organizerWebsiteUrl: "https://organizer.example.test/",
    publicId: "abc123def456",
    slug: "summer-estate-sale",
    title: "Summer Estate Sale",
    description:
      "Furniture, homewares, art, and collectibles from a family estate.",
    eventType: "ESTATE_SALE",
    origin: "OWNER_CREATED",
    localStartsAt: "2026-07-25T09:00",
    localEndsAt: "2026-07-25T15:00",
    startsAt: new Date("2026-07-25T16:00:00.000Z"),
    endsAt: new Date("2026-07-25T22:00:00.000Z"),
    timezone: "America/Los_Angeles",
    privacyMode: "EXACT_ADDRESS",
    workflowState: "PREVIEW_READY",
    approvalStatus: "NOT_APPROVED",
    version: 7,
    contentRevision: 6,
    approvedRevision: null,
    approvalDigest: null,
    approvedAt: null,
    termsVersion: null,
    termsAcceptedAt: null,
    currentApprovalId: null,
    coverPhotoId: photo.id,
    canceledAt: null,
    removedAt: null,
    createdAt: new Date("2026-07-19T00:00:00.000Z"),
    updatedAt: new Date("2026-07-20T00:00:00.000Z"),
    publication: null,
    location: {
      id: "location-1",
      eventId: "event-1",
      addressLine1: "123 Main Street",
      addressLine2: null,
      city: "Bakersfield",
      region: "CA",
      postalCode: "93301",
      countryCode: "US",
      normalizedAddress: "123 Main Street, Bakersfield, CA 93301, US",
      latitude: 35.373292,
      longitude: -119.018712,
      timezone: "America/Los_Angeles",
      providerPlaceId: "fixture.place.1",
      providerName: "test-fixture",
      providerVersion: "v1",
      providerAttribution: "Deterministic test fixture",
      resolutionSource: "ORGANIZER_AUTOCOMPLETE",
      confirmationStatus: "CONFIRMED",
      confirmedByUserId: "user-1",
      confirmedAt: new Date("2026-07-20T00:00:00.000Z"),
      publicZone: "bakersfield",
      precision: "exact",
      confidence: 1,
      validationStatus: "VERIFIED",
    },
    photos: [photo],
    ...changes,
  };
}
